### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by noamiz5060** [xiaoyeye/TFvelo#11]
I've the run_demo.py on my data and the rc.h5ad and pp.h5ad files were created without any errors. I've run the analysis and I got this error

Traceback (most recent call last):
  File "path/TFvelo/TFvelo_analysis_demo.py", line 203, in <module>
    main(args)
  File "path/TFvelo/TFvelo_analysis_demo.py", line 174, in main
    TFv.tl.velocity_graph(adata_copy, basis=None, vkey='velocity', xkey='M_total')
  File "path/TFvelo/TFvelo/tools/velocity_graph.py", line 360, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "path/TFvelo/TFvelo/tools/velocity_graph.py", line 174, in compute_cosines
    res = parallelize(
  File "path/TFvelo/TFvelo/core/_parallelize.py", line 128, in wrapper
    res = Parallel(n_jobs=n_jobs, backend=backend)(
  File "/miniconda3/envs/TFvelo_env/lib/python3.8/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/miniconda3/envs/TFvelo_env/lib/python3.8/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "path/Work/TFvelo/TFvelo/tools/velocity_graph.py", line 206, in _compute_cosines
    if self.V[obs_id].max() != 0 or self.V[obs_id].min() != 0:
  File "/miniconda3/envs/TFvelo_env/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by dsalina99** [comment]
Same issue here, I tried a different version and numpy and still get the same issue. Were you able to resolve this?

**Comment by Xiaoruipei** [comment]
Same issue here, can someone help?@xiaoyeye

**Comment by ge2sasag** [comment]
Same issue

**Comment by gargerd** [comment]
Hi everyone,

I dug deeper into this issue, and managed to get some insights:

The problem is, that when the velocity graphs are being calculated at line 173 in TFvelo_analysis_demo.py:

``` TFv.tl.velocity_graph(adata_copy, basis=None, vkey='velocity', xkey='M_total') ```

your adata_copy has 0 cells, this is causing the error. There could be 2 reasons for this, at least what I have found in my dataset:

### 1. Before running the velocity graph calculation, the ```adata_copy``` object gets thresholded like this:

```
adata_copy = get_metric_pseudotime(adata_copy)
adata_copy = adata_copy[:, adata_copy.var['spearmanr_pseudotime'] > args.spearmanr_thres] 
```
The default ```spearmanr_thres``` is 0.8. Play around with lower thresholds, so not all the cells get filtered out. Of course, I guess if you set it too low, your phase portraits are getting ugly. 

### 2. Filter out clusters, that are far away from the rest and constitute of only a single cell type.
 I found that after running ```get_pseudotime(adata)``` function, there were some NaNs in my ```adata.obs['velocity_pseudotime']```, which caused the ```get_metric_pseudotime(adata, t_key='latent_t')``` function to return all NaNs in the ```adata.var['spearmanr_pseudotime']```, which again lead to filtering out all the cells.
 
After investigating which cells had NaNs as pseudotime, I have found a cluster of Mast-cells in my case, which were far away on the UMAP from all the other cells, and were the only cell type in the cluster. I am not sure if this is specific to my dataset or not, but it is definitely worth it to check if you have cells with Nans as pseudotime. After removing these cells, the algorithm ran without issues.

I removed them by adding the line :
```adata = adata[~adata.obs['velocity_pseudotime'].isna(),:].copy()```  
after
 ```adata = get_pseudotime(adata)``` 
 in line 151.
 
As in the article the dataset consists of cells which can transition into each other, and there are no distinct high-level cell type clusters, which don't really transition into each other (i.e. immune cell cluster, endothelial cell, smooth muscle cell), I think it would make sense to run TFVelo for each high-level cell type individually, where it makes sense that there is a transition. (i.e. once for the immune cells, once for the endothelial, etc..)

@xiaoyeye please correct me if I am wrong here.

**Comment by silviettapar** [comment]
Thank you @gargerd ! Super helpful comment. In my case, I had to lower the spearmanr_thres threshold to 0.5 to get some genes.

**Comment by yoshiF7d** [comment]
Thank you very much @gargred !
