### ISSUE TITLE
get error: ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by Roger-GOAT** [xiaoyeye/TFvelo#4]
great tool! when I run analysis get error like this.
The adata file is a subset of a big file and then merge with the velocyto file.

```
(TFvelo_env) dengzhen@dengzhen-Super-Server:~/code_old/TFvelo-main$ python TFvelo_analysis_demo.py --dataset_name day2 --basis umap
------------------------------------------------------------
Namespace(basis='umap', data_path='TFvelo_day2_demo/', dataset_name='day2', layer='M_total', loss_percent_thres=50, save_name='_demo', spearmanr_thres=0.8)
Checking mt
Checking ribo
Checking hb
Checking highly_variable
Checking non_blank_gene
AnnData object with n_obs × n_vars = 5481 × 1943
    obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', 'n_counts', 'doublet_scores', 'predicted_doublets', 'doublet_info', 'batch', 'leiden', 'leiden0.8', 'leiden0.6', 'subleiden', 'celltype', 'sample_batch', 'cluster', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'initial_size_total', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'ribo', 'hb', 'n_cells_by_counts-day14', 'mean_counts-day14', 'pct_dropout_by_counts-day14', 'total_counts-day14', 'n_cells-day14', 'n_cells_by_counts-day2', 'mean_counts-day2', 'pct_dropout_by_counts-day2', 'total_counts-day2', 'n_cells-day2', 'n_cells_by_counts-day5', 'mean_counts-day5', 'pct_dropout_by_counts-day5', 'total_counts-day5', 'n_cells-day5', 'n_cells_by_counts-sham', 'mean_counts-sham', 'pct_dropout_by_counts-sham', 'total_counts-sham', 'n_cells-sham', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'Accession', 'Chromosome', 'End', 'Start', 'Strand', 'n_cells', 'n_TFs', 'fit_alpha', 'fit_beta', 'fit_omega', 'fit_theta', 'fit_gamma', 'fit_delta', 'fit_likelihood', 'fit_varx', 'fit_scaling_y', 'min_loss', 'non_blank_gene'
    uns: 'all_TFs', 'batch_colors', 'cell_phase_genes', 'celltype_colors', 'clusters_colors', 'cosg', 'dendrogram_celltype', 'genes_all', 'genes_pp', 'hvg', 'leiden', 'leiden0.6_colors', 'leiden0.8_colors', 'leiden_colors', 'log1p', 'logreg', 'neighbors', 'palantir_EigenValues', 'pca', 'rank_genes_groups', 'recover_dynamics', 'subleiden_colors', 'tsne', 'umap', 'velocity_graph', 'velocity_graph_neg', 'velocity_params', 'wilcoxon'
    obsm: 'X_palantir_diff_comp', 'X_palantir_multiscale', 'X_pca', 'X_pca_harmony', 'X_tsne', 'X_umap'
    varm: 'PCs', 'TFs', 'TFs_correlation', 'TFs_id', 'TFs_times', 'fit_scaling', 'fit_weights', 'fit_weights_final', 'fit_weights_init', 'knockTF_Log2FC', 'loss'
    layers: 'M_total', 'Ms', 'Mu', 'WX', 'ambiguous', 'filtered', 'fit_t', 'fit_t_raw', 'latent_t', 'matrix', 'palantir_imp', 'spliced', 'total', 'total_raw', 'unspliced', 'velo_hat', 'velo_normed', 'velo_t', 'velocity', 'y', 'y_t'
    obsp: 'connectivities', 'distances', 'palantir_diff_op'
computing velocity graph (using 1/48 cores)
WARNING: Unable to create progress bar. Consider installing `tqdm` as `pip install tqdm` and `ipywidgets` as `pip install ipywidgets`,
or disable the progress bar using `show_progress_bar=False`.
    finished (0:00:23) --> added 
    'velocity_graph', sparse matrix with cosine correlations (adata.uns)
saving figure to file ./figures/TFvelo_pseudotime.png
Transfering mt
Transfering ribo
Transfering hb
Transfering highly_variable
Transfering non_blank_gene
AnnData object with n_obs × n_vars = 5481 × 1943
    obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', 'n_counts', 'doublet_scores', 'predicted_doublets', 'doublet_info', 'batch', 'leiden', 'leiden0.8', 'leiden0.6', 'subleiden', 'celltype', 'sample_batch', 'cluster', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'initial_size_total', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'ribo', 'hb', 'n_cells_by_counts-day14', 'mean_counts-day14', 'pct_dropout_by_counts-day14', 'total_counts-day14', 'n_cells-day14', 'n_cells_by_counts-day2', 'mean_counts-day2', 'pct_dropout_by_counts-day2', 'total_counts-day2', 'n_cells-day2', 'n_cells_by_counts-day5', 'mean_counts-day5', 'pct_dropout_by_counts-day5', 'total_counts-day5', 'n_cells-day5', 'n_cells_by_counts-sham', 'mean_counts-sham', 'pct_dropout_by_counts-sham', 'total_counts-sham', 'n_cells-sham', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'Accession', 'Chromosome', 'End', 'Start', 'Strand', 'n_cells', 'n_TFs', 'fit_alpha', 'fit_beta', 'fit_omega', 'fit_theta', 'fit_gamma', 'fit_delta', 'fit_likelihood', 'fit_varx', 'fit_scaling_y', 'min_loss', 'non_blank_gene'
    uns: 'all_TFs', 'batch_colors', 'cell_phase_genes', 'celltype_colors', 'clusters_colors', 'cosg', 'dendrogram_celltype', 'genes_all', 'genes_pp', 'hvg', 'leiden', 'leiden0.6_colors', 'leiden0.8_colors', 'leiden_colors', 'log1p', 'logreg', 'neighbors', 'palantir_EigenValues', 'pca', 'rank_genes_groups', 'recover_dynamics', 'subleiden_colors', 'tsne', 'umap', 'velocity_graph', 'velocity_graph_neg', 'velocity_params', 'wilcoxon'
    obsm: 'X_palantir_diff_comp', 'X_palantir_multiscale', 'X_pca', 'X_pca_harmony', 'X_tsne', 'X_umap'
    varm: 'PCs', 'TFs', 'TFs_correlation', 'TFs_id', 'TFs_times', 'fit_scaling', 'fit_weights', 'fit_weights_final', 'fit_weights_init', 'knockTF_Log2FC', 'loss'
    layers: 'M_total', 'Ms', 'Mu', 'WX', 'ambiguous', 'filtered', 'fit_t', 'fit_t_raw', 'latent_t', 'matrix', 'palantir_imp', 'spliced', 'total', 'total_raw', 'unspliced', 'velo_hat', 'velo_normed', 'velo_t', 'velocity', 'y', 'y_t'
    obsp: 'connectivities', 'distances', 'palantir_diff_op'
computing velocity graph (using 1/48 cores)
Traceback (most recent call last):
  File "TFvelo_analysis_demo.py", line 202, in <module>
    main(args)
  File "TFvelo_analysis_demo.py", line 173, in main
    TFv.tl.velocity_graph(adata_copy, basis=None, vkey='velocity', xkey='M_total')
  File "/home/dengzhen/code_old/TFvelo-main/TFvelo/tools/velocity_graph.py", line 360, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/home/dengzhen/code_old/TFvelo-main/TFvelo/tools/velocity_graph.py", line 174, in compute_cosines
    res = parallelize(
  File "/home/dengzhen/code_old/TFvelo-main/TFvelo/core/_parallelize.py", line 128, in wrapper
    res = Parallel(n_jobs=n_jobs, backend=backend)(
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/dengzhen/code_old/TFvelo-main/TFvelo/tools/velocity_graph.py", line 206, in _compute_cosines
    if self.V[obs_id].max() != 0 or self.V[obs_id].min() != 0:
  File "/home/dengzhen/miniconda3/envs/TFvelo_env/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by andynkili** [comment]
@xiaoyeye, 
Thank you for this great tool.
I am experiencing the same issue.
The initial input is anndata converted from Seurat.
`TFvelo_run_demo.py` ran fine without any warnings nor errors, but the visualization ended up with the error occuring when computing the velocity graph.
The rc.h5ad looks fine:
```
>>> adata
AnnData object with n_obs × n_vars = 1473 × 2000
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'seurat_clusters', 'RNA_snn_res.0.1', 'cancer_annotation', 'grade', 'diagnosis', 'identity', 'clusters', 'n_genes', 'initial_size_total', 'initial_size', 'n_counts', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable', 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'n_TFs', 'fit_alpha', 'fit_beta', 'fit_omega', 'fit_theta', 'fit_gamma', 'fit_delta', 'fit_likelihood', 'fit_varx', 'fit_scaling_y', 'min_loss', 'non_blank_gene'
    uns: 'all_TFs', 'clusters_colors', 'genes_all', 'genes_pp', 'neighbors', 'recover_dynamics', 'velocity_graph', 'velocity_graph_neg', 'velocity_params'
    obsm: 'X_harmony', 'X_pca', 'X_pca2', 'X_umap'
    varm: 'HARMONY', 'PCA2', 'PCs', 'TFs', 'TFs_correlation', 'TFs_id', 'TFs_times', 'fit_scaling', 'fit_weights', 'fit_weights_final', 'fit_weights_init', 'knockTF_Log2FC', 'loss'
    layers: 'M_total', 'WX', 'filtered', 'fit_t', 'fit_t_raw', 'latent_t', 'total', 'total_raw', 'velo_hat', 'velo_normed', 'velo_t', 'velocity', 'y', 'y_t'
    obsp: 'connectivities', 'distances'
```
I also check `M_total` and at least it is not zero-dimension:
```
adata.layers['M_total']
array([[-0.15859047,  0.03921613, -0.02985821, ...,  0.71832615,
        -0.06404083, -0.14828354],
       [-0.15859047,  0.08192277,  0.08353867, ..., -0.23103963,
        -0.24809994,  0.06709254],
       [ 0.20730744, -0.14348184,  0.21832435, ..., -0.13461716,
        -0.06845076,  0.09948603],
       ...,
       [-0.15859047, -0.14348184,  0.0904194 , ..., -0.23103963,
        -0.33989397,  0.3065972 ],
       [-0.15859045, -0.14348184, -0.15728725, ...,  0.06337859,
         0.05384813,  0.01863561],
       [-0.15859047,  0.09579182, -0.15728725, ...,  0.12107909,
        -0.04139335,  0.39589158]], dtype=float32)
```
I also tried with another dataset converted from Seurat and same thing happened.
Do you have any clues about what could be causing this issue?

Best,
Andy

**Comment by dsalina99** [comment]
> @xiaoyeye great tool! when I run analysis get error like this. The adata file is a subset of a big file and then merge with the velocyto file.
> 
> ```
> (TFvelo_env) dengzhen@dengzhen-Super-Server:~/code_old/TFvelo-main$ python TFvelo_analysis_demo.py --dataset_name day2 --basis umap
> ------------------------------------------------------------
> Namespace(basis='umap', data_path='TFvelo_day2_demo/', dataset_name='day2', layer='M_total', loss_percent_thres=50, save_name='_demo', spearmanr_thres=0.8)
> Checking mt
> Checking ribo
> Checking hb
> Checking highly_variable
> Checking non_blank_gene
> AnnData object with n_obs × n_vars = 5481 × 1943
>     obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', 'n_counts', 'doublet_scores', 'predicted_doublets', 'doublet_info', 'batch', 'leiden', 'leiden0.8', 'leiden0.6', 'subleiden', 'celltype', 'sample_batch', 'cluster', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'initial_size_total', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime'
>     var: 'gene_ids', 'feature_types', 'genome', 'mt', 'ribo', 'hb', 'n_cells_by_counts-day14', 'mean_counts-day14', 'pct_dropout_by_counts-day14', 'total_counts-day14', 'n_cells-day14', 'n_cells_by_counts-day2', 'mean_counts-day2', 'pct_dropout_by_counts-day2', 'total_counts-day2', 'n_cells-day2', 'n_cells_by_counts-day5', 'mean_counts-day5', 'pct_dropout_by_counts-day5', 'total_counts-day5', 'n_cells-day5', 'n_cells_by_counts-sham', 'mean_counts-sham', 'pct_dropout_by_counts-sham', 'total_counts-sham', 'n_cells-sham', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'Accession', 'Chromosome', 'End', 'Start', 'Strand', 'n_cells', 'n_TFs', 'fit_alpha', 'fit_beta', 'fit_omega', 'fit_theta', 'fit_gamma', 'fit_delta', 'fit_likelihood', 'fit_varx', 'fit_scaling_y', 'min_loss', 'non_blank_gene'
>     uns: 'all_TFs', 'batch_colors', 'cell_phase_genes', 'celltype_colors', 'clusters_colors', 'cosg', 'dendrogram_celltype', 'genes_all', 'genes_pp', 'hvg', 'leiden', 'leiden0.6_colors', 'leiden0.8_colors', 'leiden_colors', 'log1p', 'logreg', 'neighbors', 'palantir_EigenValues', 'pca', 'rank_genes_groups', 'recover_dynamics', 'subleiden_colors', 'tsne', 'umap', 'velocity_graph', 'velocity_graph_neg', 'velocity_params', 'wilcoxon'
>     obsm: 'X_palantir_diff_comp', 'X_palantir_multiscale', 'X_pca', 'X_pca_harmony', 'X_tsne', 'X_umap'
>     varm: 'PCs', 'TFs', 'TFs_correlation', 'TFs_id', 'TFs_times', 'fit_scaling', 'fit_weights', 'fit_weights_final', 'fit_weights_init', 'knockTF_Log2FC', 'loss'
>     layers: 'M_total', 'Ms', 'Mu', 'WX', 'ambiguous', 'filtered', 'fit_t', 'fit_t_raw', 'latent_t', 'matrix', 'palantir_imp', 'spliced', 'total', 'total_raw', 'unspliced', 'velo_hat', 'velo_normed', 'velo_t', 'velocity', 'y', 'y_t'
>     obsp: 'connectivities', 'distances', 'palantir_diff_op'
> computing velocity graph (using 1/48 cores)
> WARNING: Unable to create progress bar. Consider installing `tqdm` as `pip install tqdm` and `ipywidgets` as `pip install ipywidgets`,
> or disable the progress bar using `show_progress_bar=False`.
>     finished (0:00:23) --> added 
>     'velocity_graph', sparse matrix with cosine correlations (adata.uns)
> saving figure to file ./figures/TFvelo_pseudotime.png
> Transfering mt
> Transfering ribo
> Transfering hb
> Transfering highly_variable
> Transfering non_blank_gene
> AnnData object with n_obs × n_vars = 5481 × 1943
>     obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', 'n_counts', 'doublet_scores', 'predicted_doublets', 'doublet_info', 'batch', 'leiden', 'leiden0.8', 'leiden0.6', 'subleiden', 'celltype', 'sample_batch', 'cluster', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'initial_size_total', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime'
>     var: 'gene_ids', 'feature_types', 'genome', 'mt', 'ribo', 'hb', 'n_cells_by_counts-day14', 'mean_counts-day14', 'pct_dropout_by_counts-day14', 'total_counts-day14', 'n_cells-day14', 'n_cells_by_counts-day2', 'mean_counts-day2', 'pct_dropout_by_counts-day2', 'total_counts-day2', 'n_cells-day2', 'n_cells_by_counts-day5', 'mean_counts-day5', 'pct_dropout_by_counts-day5', 'total_counts-day5', 'n_cells-day5', 'n_cells_by_counts-sham', 'mean_counts-sham', 'pct_dropout_by_counts-sham', 'total_counts-sham', 'n_cells-sham', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'Accession', 'Chromosome', 'End', 'Start', 'Strand', 'n_cells', 'n_TFs', 'fit_alpha', 'fit_beta', 'fit_omega', 'fit_theta', 'fit_gamma', 'fit_delta', 'fit_likelihood', 'fit_varx', 'fit_scaling_y', 'min_loss', 'non_blank_gene'
>     uns: 'all_TFs', 'batch_colors', 'cell_phase_genes', 'celltype_colors', 'clusters_colors', 'cosg', 'dendrogram_celltype', 'genes_all', 'genes_pp', 'hvg', 'leiden', 'leiden0.6_colors', 'leiden0.8_colors', 'leiden_colors', 'log1p', 'logreg', 'neighbors', 'palantir_EigenValues', 'pca', 'rank_genes_groups', 'recover_dynamics', 'subleiden_colors', 'tsne', 'umap', 'velocity_graph', 'velocity_graph_neg', 'velocity_params', 'wilcoxon'
>     obsm: 'X_palantir_diff_comp', 'X_palantir_multiscale', 'X_pca', 'X_pca_harmony', 'X_tsne', 'X_umap'
>     varm: 'PCs', 'TFs', 'TFs_correlation', 'TFs_id', 'TFs_times', 'fit_scaling', 'fit_weights', 'fit_weights_final', 'fit_weights_init', 'knockTF_Log2FC', 'loss'
>     layers: 'M_total', 'Ms', 'Mu', 'WX', 'ambiguous', 'filtered', 'fit_t', 'fit_t_raw', 'latent_t', 'matrix', 'palantir_imp', 'spliced', 'total', 'total_raw', 'unspliced', 'velo_hat', 'velo_normed', 'velo_t', 'velocity', 'y', 'y_t'
>     obsp: 'connectivities', 'distances', 'palantir_diff_op'
> computing velocity graph (using 1/48 cores)
> Traceback (most recent call last):
>   File "TFvelo_analysis_demo.py", line 202, in <module>
>     main(args)
>   File "TFvelo_analysis_demo.py", line 173, in main
>     TFv.tl.velocity_graph(adata_copy, basis=None, vkey='velocity', xkey='M_total')
>   File "/home/dengzhen/code_old/TFvelo-main/TFvelo/tools/velocity_graph.py", line 360, in velocity_graph
>     vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
>   File "/home/dengzhen/code_old/TFvelo-main/TFvelo/tools/velocity_graph.py", line 174, in compute_cosines
>     res = parallelize(
>   File "/home/dengzhen/code_old/TFvelo-main/TFvelo/core/_parallelize.py", line 128, in wrapper
>     res = Parallel(n_jobs=n_jobs, backend=backend)(
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1085, in __call__
>     if self.dispatch_one_batch(iterator):
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 819, in _dispatch
>     job = self._backend.apply_async(batch, callback=cb)
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
>     result = ImmediateResult(func)
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 597, in __init__
>     self.results = batch()
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 288, in __call__
>     return [func(*args, **kwargs)
>   File "/home/dengzhen/.local/lib/python3.8/site-packages/joblib/parallel.py", line 288, in <listcomp>
>     return [func(*args, **kwargs)
>   File "/home/dengzhen/code_old/TFvelo-main/TFvelo/tools/velocity_graph.py", line 206, in _compute_cosines
>     if self.V[obs_id].max() != 0 or self.V[obs_id].min() != 0:
>   File "/home/dengzhen/miniconda3/envs/TFvelo_env/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
>     return umr_maximum(a, axis, None, out, keepdims, initial, where)
> ValueError: zero-size array to reduction operation maximum which has no identity
> ```

Same issue here, I tried a different version and numpy and still get the same issue. Were you able to resolve this?

**Comment by dsalina99** [comment]
> Same issue here, I tried a different version and numpy and still get the same issue. Were you able to resolve this?

**Comment by Xiaoruipei** [comment]
@xiaoyeye,
Thank you for this great tool.
Same issue here, have you ever sole this problem? @dsalina99 @Roger-GOAT @andynkili

**Comment by ATPs** [comment]
same issue.

**Comment by ATPs** [comment]
@dsalina99 @Roger-GOAT @andynkili @xiaoyeye 
 After running the scripts step by step, I found two possible place causing the error. it seems that during running the steps below, zero genes left.

```Python
adata_copy = ad.read_h5ad(result_path + 'rc.h5ad')
adata_copy = adata_copy[:, adata_copy.var['n_cells'] > thres_n_cells]

adata_copy = adata_copy[:, adata_copy.var['non_blank_gene']==0] 


adata_copy = get_metric_pseudotime(adata_copy)
adata_copy = adata_copy[:, adata_copy.var['spearmanr_pseudotime'] > spearmanr_thres] 
```

one step with the line
```python
adata_copy = adata_copy[:, adata_copy.var['non_blank_gene']==0] 

```
may need to change to 

```python
adata_copy = adata_copy[:, (adata_copy.var['non_blank_gene']==0) | (adata_copy.var['non_blank_gene']=='False')] 

```
because the value in this column is catogorical, and `==0` may not work with some version of pandas or numpy, I guess.

Another place to change is the "args.spearmanr_thres". if this value is too big, no gene will left.

Not sure if I understanding is correct, but I can get some figures.
