### ISSUE TITLE
import TFvelo as TFv

### ISSUE THREAD

**Issue by hyg200100** [xiaoyeye/TFvelo#6]
Hi all,

I hope this message finds you well. I am writing to inquire about the installation process for the TFvelo code. I have been trying to import the TFvelo module using "import TFvelo as TFv" in my Python script, but it appears that the TFvelo module is not available for installation through standard channels like pip.

I have searched for the module on PyPI and other package repositories, but couldn't find a matching distribution. Could you please provide guidance on how to obtain and install the TFvelo module?

I have already obtained the TFvelo code from the repository [repository URL] and downloaded it to my local machine. However, I am unsure of the correct installation procedure. Could you kindly provide instructions on how to install TFvelo or any specific dependencies that need to be satisfied beforehand?

Thank you very much for your time and attention. I greatly appreciate any assistance you can provide in helping me install TFvelo and utilize its functionalities effectively.

Looking forward to your kind response.

Best regards,hyg

**Comment by noamiz5060** [comment]
did you manage to solve this? I have the same problem

**Comment by Xiaoruipei** [comment]
when I try import TFvelo, i got this error. can anyone help, thanks. @xiaoyeye 

>>> import TFvelo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/administrator/TFvelo/TFvelo/__init__.py", line 3, in <module>
    from scanpy import read, read_loom
  File "/home/administrator/anaconda3/envs/TFvelo_env/lib/python3.8/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/home/administrator/anaconda3/envs/TFvelo_env/lib/python3.8/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/home/administrator/anaconda3/envs/TFvelo_env/lib/python3.8/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/home/administrator/anaconda3/envs/TFvelo_env/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by AAA-3** [comment]
Similar to issue #2 but there the solution is also not the best
